packages:
  python-dateutil:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '*dateutil-zoneinfo.tar.gz'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  matplotlib:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '**/matplotlib/mpl-data/**'
      - pattern: '**/matplotlib/fontlist.json'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  scikit-learn:
    include_patterns:
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '**/sklearn/datasets/**'
    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
  ipympl:
    include_patterns:
      - pattern: '*.py'
      - pattern: '**/ipympl/static'
  scikit-image:
    include_patterns:
      - pattern: '*'
      - pattern: '*.so'
      - pattern: '*.py'
      - pattern: '**/skimage/data/**'
      - pattern: '**/skimage/io/_plugins/*.ini'

    exclude_patterns:
      - pattern: '**/tests/**/*.py'
      - pattern: '**/tests/**/*.so'
default:
  include_patterns:
    - pattern: '*.so'
    - pattern: '*.py'
  exclude_patterns:
    - pattern: '**/tests/**/*.py'
    - pattern: '**/tests/**/*.so'
