[workspace]
name = "emscripten-forge"
version = "0.1.0"
description = "The emscripten-forge for emscripten-wasm32- builds."
authors = ["DerThorsten <derthorstenbeier@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64"]

# default environment
[dependencies]
rattler-build = ">=0.34.1"
curl = "*"

############################################
# rattler-build feature / tasks
############################################
[feature.feature_rattler_build]
[feature.feature_rattler_build.dependencies]
git = "*"
patch = "*"
rattler-build = ">=0.34.1"
python = "3.11.*"
typer = "*"
curl = "*"

[feature.feature_rattler_build.tasks.build-emscripten-compiler-pkg]
cmd = [
    "rattler-build","build",
    # format
    "--package-format", "tar-bz2",
    # channels
    "-c", "https://repo.prefix.dev/emscripten-forge-4x",
    "-c", "microsoft",
    "-c", "conda-forge",
    "--skip-existing", "all",
    "-m", "variant.yaml",
    "--recipe",
    "recipes/recipes/emscripten_emscripten-wasm32"
]

[feature.feature_rattler_build.tasks.build-cross-python-pkg]
cmd = [
    "rattler-build","build",
    # format
    "--package-format", "tar-bz2",
    # channels
    "-c", "https://repo.prefix.dev/emscripten-forge-4x",
    "-c", "microsoft",
    "-c", "conda-forge",
    "--skip-existing", "all",
    "-m", "variant.yaml",
    "--recipe",
    "recipes/recipes/cross-python_emscripten-wasm32"
]

[feature.feature_rattler_build.tasks.build-pytester-pkg]
cmd = [
    "rattler-build","build",
    # format
    "--package-format", "tar-bz2",
    # channels
    "-c", "https://repo.prefix.dev/emscripten-forge-4x",
    "-c", "microsoft",
    "-c", "conda-forge",
    "--skip-existing", "all",
    "-m", "variant.yaml",
    "--recipe",
    "recipes/recipes/pytester"
]


[feature.feature_rattler_build.tasks.setup]
depends-on = ["build-emscripten-compiler-pkg", "build-cross-python-pkg", "build-pytester-pkg"]


[feature.feature_rattler_build.tasks.build-emscripten-wasm32-pkg]
cmd = [
    "rattler-build","build",
    # format
    "--package-format", "tar-bz2",
    # channels
    "-c", "https://repo.prefix.dev/emscripten-forge-4x",
    "-c", "microsoft",
    "-c", "conda-forge",
    "--target-platform", "emscripten-wasm32",
    "--skip-existing", "none",
    "-m", "variant.yaml",
    "--recipe"
]

[feature.feature_rattler_build.tasks.build-pkg]
cmd = [
    "rattler-build","build",
    # format
    "--package-format", "tar-bz2",
    # channels
    "-c", "https://repo.prefix.dev/emscripten-forge-4x",
    "-c", "microsoft",
    "-c", "conda-forge",
    "--skip-existing", "all",
    "-m", "variant.yaml",
    "--recipe"
]


############################################
# documentation feature / tasks
############################################
[feature.feature_documentation]
[feature.feature_documentation.dependencies]
python = "3.11.*"
mkdocs = ">=1.6.0"
mkdocs-material = ">=9.5.2"
pip = "*"
mkdocs-git-committers-plugin-2 = "*"


[feature.feature_documentation.tasks.docs-serve]
cmd = ["mkdocs", "serve"]

[feature.feature_documentation.tasks.docs-build]
cmd = ["mkdocs", "build"]

############################################
# environments
############################################

[environments]
rattler-build-env = ["feature_rattler_build"]
documentation-env = ["feature_documentation"]
