packages:
  # Exclude R packages from pyarrow tests
  # These are only needed for r-arrow output, not for pyarrow
  r-base:
    exclude_patterns:
      - pattern: '**'
  r-base-abi:
    exclude_patterns:
      - pattern: '**'
  r-assertthat:
    exclude_patterns:
      - pattern: '**'
  r-bit64:
    exclude_patterns:
      - pattern: '**'
  r-cpp11:
    exclude_patterns:
      - pattern: '**'
  r-glue:
    exclude_patterns:
      - pattern: '**'
  r-purrr:
    exclude_patterns:
      - pattern: '**'
  r-r6:
    exclude_patterns:
      - pattern: '**'
  r-rlang:
    exclude_patterns:
      - pattern: '**'
  r-tidyselect:
    exclude_patterns:
      - pattern: '**'
  r-vctrs:
    exclude_patterns:
      - pattern: '**'
default:
  exclude_patterns:
    - pattern: 'bin/**'
    - pattern: '**/bin/**'
    - pattern: 'tests/**'
    - pattern: '**/*.exe'
    - pattern: '**/*.c'
    - pattern: '**/*.pxd'
    - pattern: '**/*.pyx'
    - pattern: '**/*.pyc'
    - pattern: '**/*.typed'
    - pattern: '**/*.egg-info'
    - pattern: '**/site-packages/pip/_vendor/**'
    - pattern: '**/idlelib/**'
    - pattern: '**/ensurepip/**'
    - pattern: 'Scripts/*'
    - pattern: 'share/jupyter/nbextensions/**'
    - pattern: 'share/jupyter/labextensions/**'
    - pattern: 'etc/jupyter/nbconfig/**'
