c_compiler: emscripten
c_compiler_version: 3.1.73
channel_targets: conda-forge main
cxx_compiler: emscripten
cxx_compiler_version: 3.1.73
numpy: '2.2'
python: 3.13.* *_cp313
target_platform: emscripten-wasm32
