name: Version Ticker Bot

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  update_versions:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: tickbot.yml

      - name: Determine new package version and open/merge PRs
        shell: bash -l -eo pipefail {0}
        run: python bump_recipes_versions.py
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
