name: Version Ticker Bot

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  update_versions:
    if: (github.event_name == 'schedule' && github.repository == 'emscripten-forge/recipes') || (github.event_name != 'schedule')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci_env.yml

      - name: Determine new package version and open/merge PRs
        shell: bash -l -eo pipefail {0}
        run:  python -m emci bot bump-recipes-versions
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
v