name: Matplotlib Fontcache Update Bot

on:
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:

  update_matplotlib_fontcache:
    strategy:
      matrix:
        branch: [main, emscripten-4x]

    if: (github.event_name == 'schedule' && github.repository == 'emscripten-forge/recipes') || (github.event_name != 'schedule')
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ matrix.branch }}

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ci_env.yml
          create-args: >-
            microsoft::playwright
            pyjs_code_runner

      - name: Update matplotlib font cache if needed
        shell: bash -l -eo pipefail {0}
        run: |
          playwright install
          python -m emci bot update-matplotlib-fontcache ${{ matrix.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
